### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [Alustrat/al-magic#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by Alustrat** [comment]
Hey @unixorn, thanks for the proposition. I put the License as you requested and made a screenshot with some command ouputs. Don't hesitate to come back to me if you want more specific commands to be visible on the picture.

Also you should know that I just started this theme and it might be possible that I keep evolving it and add changes in the future.

Best 😊

**Comment by unixorn** [comment]
Thanks, adding. No worries about evolving the theme, if you ever change the name, open an issue or PR on [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) so that it gets updated in the list.
